---

- name: Pull admin identity from the wallet
  include_role: 
    name: wallet
  vars:
    wallet_ops: "get"
    wallet_path: "{{ msp_admin_id }}"

- set_fact:
    msp_admin: "{{wallet_fetched_identity_dict}}"
  no_log: true

- name: Pull admin identity from the wallet
  include_role: 
    name: wallet
  vars:
    wallet_ops: "get"
    wallet_path: "{{ msp_admin_tls_id }}"

- set_fact:
    msp_admin_tls: "{{ wallet_fetched_identity_dict }}"
  no_log: true

- name: "Fail if channel_name is empty"
  fail:
     msg: "Please define the name of the channel"
  when: channel_name == ""

- name: Preapre channel block file directory
  file:
    state: directory
    path: "{{channel_file_directory}}"

- name: Delete any old channel block file
  file:
    state: absent
    path: "{{channel_file_directory}}/{{channel_name}}"

- set_fact:
    msp_id.ca: "{{ 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNIVENDQWNPZ0F3SUJBZ0lVZnRGcGdyZ3ZkejBmYWhLYnV0V1p0aUh2UmhFd0NnWUlLb1pJemowRUF3SXcKWkRFTE1Ba0dBMVVFQmhNQ1ZWTXhGekFWQmdOVkJBZ1REazV2Y25Sb0lFTmhjbTlzYVc1aE1SUXdFZ1lEVlFRSwpFd3RJZVhCbGNteGxaR2RsY2pFUE1BMEdBMVVFQ3hNR1JtRmljbWxqTVJVd0V3WURWUVFERXd4aGJuTnBZbXhsClkyRXRZMkV3SGhjTk1qTXdNekF6TVRreE1qQXdXaGNOTXpnd01qSTNNVGt4TWpBd1dqQmtNUXN3Q1FZRFZRUUcKRXdKVlV6RVhNQlVHQTFVRUNCTU9UbTl5ZEdnZ1EyRnliMnhwYm1FeEZEQVNCZ05WQkFvVEMwaDVjR1Z5YkdWawpaMlZ5TVE4d0RRWURWUVFMRXdaR1lXSnlhV014RlRBVEJnTlZCQU1UREdGdWMybGliR1ZqWVMxallUQlpNQk1HCkJ5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCQXFLSEo2VGZFSGlaS0I0NjRiWVVjQ3NGMU8vc0JKUStHRXIKaGxUTWNtM1VuQVpCR1dUMkpIY1h0LzM2bHdNUGdkMWNmQkZTOVE1TXUzRXMrb1U5Tm11alV6QlJNQTRHQTFVZApEd0VCL3dRRUF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVdCQlNHNXRScFYvZGxqamVaCmRpYmpwNU1vdjB5aHpEQVBCZ05WSFJFRUNEQUdod1IvQUFBQk1Bb0dDQ3FHU000OUJBTUNBMGdBTUVVQ0lRRFkKZ0FUUGx2bmdoanMrWVFNVVF2Z1VsZVIvc2E2S0FaeHRKSk1Nd1JKaUV3SWdHTzc1VVdjWUNjbzhzbDM3UFZlZQpuTGI0UmkycFlSWTA1a2Flcm81bXFHWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=' | b64decode }}"

- name: Fetch channel
  ibm.blockchain_platform.channel_block:
    api_endpoint: "{{ console_api_endpoint }}"
    api_authtype: "{{ console_api_authtype }}"
    api_key: "{{ console_username }}"
    api_secret: "{{ console_password | default(omit) }}"
    #api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    operation: fetch
    ordering_service: "{{ ordering_service_name }}"
    identity: "{{ msp_admin }}"
    msp_id: "{{ msp_id }}"
    name: "{{ channel_name }}"
    target: "0"
    path: "{{channel_file_directory}}/{{channel_name}}"
  failed_when: False
  register: result

- debug:
    var: result

# - name: "Fail on any error other than the channel not existing"
#   fail:
#     msg: "{{ result.msg }}"
#   when: result.msg is defined and 'NOT_FOUND' not in result.msg

# - name: "Create the configuration update for the new channel"
#   ibm.blockchain_platform.channel_config:
#     api_endpoint: "{{ api_endpoint }}"
#     api_authtype: "{{ api_authtype }}"
#     api_key: "{{ api_key }}"
#     api_secret: "{{ api_secret | default(omit) }}"
#     api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
#     operation: create
#     name: "{{ channel_name }}"
#     path: config_update.bin
#     organizations:
#       - "{{ organization_name }}"
#     policies:
#       Admins: "{{ lookup('template', 'admins-policy.json.j2') }}"
#       Readers: "{{ lookup('template', 'readers-policy.json.j2') }}"
#       Writers: "{{ lookup('template', 'writers-policy.json.j2') }}"
#       Endorsement: "{{ lookup('template', 'endorsement-policy.json.j2') }}"
#       LifecycleEndorsement: "{{ lookup('template', 'lifecycle-endorsement-policy.json.j2') }}"
#     capabilities:
#       application: V2_0
#   when: result.msg is defined and 'NOT_FOUND' in result.msg

# - name: "Sign the channel configuration update for the new channel"
#   ibm.blockchain_platform.channel_config:
#     operation: sign_update
#     identity: "{{ organization_name }}admin.json"
#     msp_id: "{{ msp_id }}"
#     name: "{{ channel_name }}"
#     path: config_update.bin
#   when: result.msg is defined and 'NOT_FOUND' in result.msg

# - name: "Apply the channel configuration update for the new channel"
#   ibm.blockchain_platform.channel_config:
#     api_endpoint: "{{ api_endpoint }}"
#     api_authtype: "{{ api_authtype }}"
#     api_key: "{{ api_key }}"
#     api_secret: "{{ api_secret | default(omit) }}"
#     api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
#     operation: apply_update
#     ordering_service: "{{ ordering_service_name }}"
#     identity: "{{ organization_name }}admin.json"
#     msp_id: "{{ msp_id }}"
#     name: "{{ channel_name }}"
#     path: config_update.bin
#   when: result.msg is defined and 'NOT_FOUND' in result.msg
