- name: "Read json files identities"
  slurp:
    src: "{{ item }}"
  loop:
    - "{{ msp_id }}admin.json"
    - "{{ certificate_authority }}admin.json"
  register: admin_json_result

- set_fact:
    admin_identity_json: 
      data: "{{admin_json_result.results[0].content | b64decode | from_json }}"
      id: "{{org_admin_identity_id}}"

- name: "Store org admin identity"
  include_tasks: "store-admin-identity.yml"

- set_fact:
    admin_identity_json: 
      data: "{{admin_json_result.results[1].content | b64decode | from_json }}"
      id: "{{org_ca_admin_identity_id}}"

- name: "Store ca admin identity"
  include_tasks: "store-admin-identity.yml"

# cleanup
- name: "Cleanup files"
  file:
    state: absent
    path: "{{item}}"
  with_items:
    - "{{msp_id}}admin.json"
    - "{{certificate_authority}}admin.json"
