---
  - name: register temporary directory
    tempfile:
      state: directory
    register: tmp_directory

  - name: check azure cli
    stat:
      path: "{{ azure_cli.bin_directory }}/azure"
    register: azure_cli_stat_result
    tags:
      - azure_cli

  - name: Ensures bin dir exists
    become: true
    file:
      path: "{{ azure_cli.bin_directory | default(default.bin_directory) }}"
      recurse: yes
      mode: '0755'
      state: directory

  - name: install azure cli
    become: true
    shell: |
      cd "{{ tmp_directory.path }}"
      curl -L https://aka.ms/InstallAzureCli | bash

