---
- name: "Get the organization"
  ibm.blockchain_platform.organization_info:
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    name: "{{ organization_name }}"
  register: result


- name: "Fail if the organization does not exist"
  fail:
    msg: "Organization {{ organization_name }} does not exist"
  when: not result.exists

- name: "Store the organization in a file"
  copy:
    content: "{{ result.organization | to_nice_json }}"
    dest: "{{ organization_name }}.json"

- name: "Upload exported organisation"
  include_role:
    name: git-config
  vars:
    git_push: true
    git_src_file: "./{{organization_name}}.json"
