- set_fact:
    wallet_resource_path: "{{vault_config.vaultPath}}/{{wallet_path}}"

- name: Fetch identity certs from Vault {{ vault_config.url }} with path {{ wallet_resource_path }}
  community.hashi_vault.vault_kv2_get:
    url: "{{ vault_config.url }}"
    path: "{{ wallet_resource_path }}"
    engine_mount_point: "{{vault_engine_mount}}"
    auth_method: userpass
    username: "{{ vault_config.username }}"
    password: "{{ vault_config.password }}"
    validate_certs: false
  register: wallet_fetched_identity

- debug:
    msg: "{{wallet_fetched_identity}}"
- set_fact:
    wallet_fetched_identity_dict: "{{ wallet_fetched_identity.data.data.data | regex_replace('\\n', '\n') | from_json }}"

- set_fact:
    wallet_operator_identity_dict:
      cert: "{{wallet_fetched_identity_dict.credentials.certificate}}"
      provate_key: "{{wallet_fetched_identity_dict.credentials.private_key}}"
      ca: "{{ wallet_fetched_identity.data.ca.data | b64decode }}"