ordererorg_domain: "openidl.testnet.openidl.org"
domain: "openidl.testnet.openidl.org"
internal_domain: "internal.openidl.testnet.openidl.org"
node_type: "carrier"
network:
  org_name: "openidl"
  ordererorg: "true"
  ordererorg_name: "ord"
  organizations:
    - name: "openidl"
      domain: "openidl.testnet.openidl.org"
  channels:
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: bitbucket.org/senofi/openidl-openidl-main.git
      repo_branch: testnet
      repo_path: openidl-chaincode/chaincode/openidl
  - name: analytics-aais
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: bitbucket.org/senofi/openidl-openidl-main.git
      repo_branch: testnet
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "analytics_aais_pdc"
          policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
  - name: analytics-carrier01
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: bitbucket.org/senofi/openidl-openidl-main.git
      repo_branch: testnet
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_cnd_pdc"
          policy: "OR('analyticsMSP.member', 'cndMSP.member')"
  - name: openidl-health
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: bitbucket.org/senofi/openidl-openidl-main.git
      repo_branch: testnet
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_cnd_pdc"
          policy: "OR('analyticsMSP.member', 'cndMSP.member')"

  - name: openidl-playground
    chaincode:
      name: openidl-test-fabcar
      repo_url: github.com/hyperledger/fabric-samples.git
      repo_branch: release-2.2
      repo_path: asset-transfer-basic/chaincode-go
      arguments: '{"function":"CreateAsset","Args":["asset1","blue",10,"Org1User1",120]}'