ordererorg_domain: "openidl.testnet.openidl.org"
domain: "openidl.testnet.openidl.org"
internal_domain: "internal.openidl.testnet.openidl.org"
node_type: "carrier"
network:
  org_name: "openidl"
  ordererorg: "true"
  ordererorg_name: "openidl-orderer"
  organizations:
    - name: "openidl"
      domain: "openidl.testnet.openidl.org"
  channels:
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: bitbucket.org/senofi/openidl-openidl-main.git
      repo_branch: testnet
      repo_path: openidl-chaincode/chaincode/openidl
  - name: analytics-aais
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: bitbucket.org/senofi/openidl-openidl-main.git
      repo_branch: testnet
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "analytics_aais_pdc"
          policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
  - name: analytics-carrier01
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: bitbucket.org/senofi/openidl-openidl-main.git
      repo_branch: testnet
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_cnd_pdc"
          policy: "OR('analyticsMSP.member', 'cndMSP.member')"
