ordererorg_domain: "testnet.openidl.org"
domain: "testnet.openidl.org"
internal_domain: "internal.testnet.openidl.org"
node_type: "carrier"
network:
  org_name: "openidl_test"
  ordererorg: "true"
  ordererorg_name: "openidl_test_orderer"
  organizations: []
  channels:
  - name: defaultchannel
    chaincode:
      name: openidl-cc-default
      repo_url: bitbucket.org/senofi/openidl-openidl-main.git
      repo_branch: openidl-nd-poc-main
      repo_path: openidl-chaincode/chaincode/openidl
  - name: analytics-aais
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: bitbucket.org/senofi/openidl-openidl-main.git
      repo_branch: openidl-nd-poc-main
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "analytics_aais_pdc"
          policy: "OR('analyticsMSP.member', 'aaisMSP.member')"
  - name: analytics-cnd
    chaincode:
      name: openidl-cc-aais-carriers
      repo_url: github.com/openidl-org/openidl-main.git
      repo_branch: openidl-nd-poc-main
      repo_path: openidl-chaincode/chaincode/openidl
      collectionconfig:
        - name: "anal_cnd_pdc"
          policy: "OR('analyticsMSP.member', 'cndMSP.member')"
