---
  - name: register temporary directory
    tempfile:
      state: directory
    register: tmp_directory
    tags:
      - molecule-idempotence-notest

  - name: Ensures bin dir exists
    become: true
    file:
      path: "{{ kubectl.bin_directory | default(default.bin_directory) }}"
      recurse: yes
      mode: '0755'
      state: directory

  - name: check kubectl
    stat:
      path: "{{ kubectl.bin_directory | default(default.bin_directory) }}/kubectl"
    register: kubectl_stat_result
    tags:
      - kubectl

  - name: "Get kubectl stable version"
    set_fact:
      kubectl_stable_version: "{{ lookup('url', 'https://dl.k8s.io/release/stable.txt')}}"
    when: not kubectl_stat_result.stat.exists
    tags:
      - kubectl

  - name: Download kubectl binary
    become: true
    get_url:
      url: "https://dl.k8s.io/release/{{kubectl_stable_version}}/bin/{{install_os}}/{{install_arch}}/kubectl"
      dest: "{{ kubectl.bin_directory | default(default.bin_directory) }}/kubectl"
      checksum: ""
    when: not kubectl_stat_result.stat.exists
    tags:
      - kubectl

  - name: Test kubectl installation
    command: "{{ kubectl.bin_directory | default(default.bin_directory) }}/kubectl version --client --short"
    changed_when: false
    tags:
      - molecule-idempotence-notest

  - name: Changing the current context namespace to default
    shell: |
      KUBECONFIG={{ item.k8s.config_file }} kubectl config set-context --current --namespace=default
    when: item is defined and item.k8s is defined
    tags:
      - molecule-idempotence-notest
