apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: openidl-metrics
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus
  chart:
    git: https://github.com/prometheus-community/helm-charts.git
    ref: prometheus-15.16.0
    path: charts/prometheus
  values:
    serviceAccounts:
      alertmanager:
        create: false
      nodeExporter:
        create: false
      pushgateway:
        create: false
    alertmanager:
      enabled: false
    kube-state-metrics:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    pushgateway:
      enabled: false
    server:
      extraArgs: { log.level: debug }
      remoteWrite:
        - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
          remote_timeout: 30s
          write_relabel_configs:
          - source_labels: [__name__]
            regex: "channel|host|topic|broker_id|version|service|method|code|level|chaincode|success|type|function_name|database|filtered|data_type|chaincodeerror|transaction_type|validation_code"
            action: keep
          basic_auth:
            username: 610199
            password: eyJrIjoiNjZlMmE4NTA4ZDljNzUwNDY1OGIwZTE0MjEyY2E1MGVlZjlhN2Y5YSIsIm4iOiJzdGFjay00NTQ3MTQtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjcyNjU0M30=
      persistentVolume:
        storageClass: gp2

