apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: openidl-metrics
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus
  chart:
    git: https://github.com/prometheus-community/helm-charts.git
    ref: prometheus-15.16.0
    path: charts/prometheus
  values:
    serviceAccounts:
      alertmanager:
        create: false
      nodeExporter:
        create: false
      pushgateway:
        create: false
    alertmanager:
      enabled: false
    pushgateway:
      enabled: false
    nodeExporter:
      enabled: false
    server:
      configFromSecret: "prom-conf"
#      configPath: /etc/config/prometheus.yml
      persistentVolume:
        enabled: false