apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus-community/prometheus
  namespace: openidl-metrics
  annotations:
    fluxcd.io/automated: "false"
spec:
  chart:
    git: https://github.com/prometheus-community/helm-charts.git
    ref: prometheus-15.16.0
    path: charts/prometheus
  values:
    server:
      extraSecretMounts:
         - name: prometheus-config
           mountPath: /etc/config/prometheus.yml
           subPath: ""
           secretName: prom-config
           readOnly: true
