apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: openidl-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: prometheus
  chart:
    git: https://github.com/prometheus-community/helm-charts.git
    ref: prometheus-15.16.0
    path: charts/prometheus
  values:
    serviceAccounts:
      alertmanager:
        create: false
      nodeExporter:
        create: false
      pushgateway:
        create: false
    alertmanager:
      enabled: false
    pushgateway:
      enabled: false
    nodeExporter:
      enabled: false
    server:
      extraArgs: { log.level: debug }
      remote_write:
        - url: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
          basic_auth:
            username: 610199
            password: eyJrIjoiNjZlMmE4NTA4ZDljNzUwNDY1OGIwZTE0MjEyY2E1MGVlZjlhN2Y5YSIsIm4iOiJzdGFjay00NTQ3MTQtZWFzeXN0YXJ0LXByb20tcHVibGlzaGVyIiwiaWQiOjcyNjU0M30=
      persistentVolume:
        storageClass: gp2

