---
- name: Get mongodb user name
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ org_id }}-{{ env_id}}-mongodb-user"
  register: mongodb_user_out

- name: Set mongodb user name
  no_log: "{{hide_sensitive_logs}}"
  set_fact:
    mongodb_user: "{{mongodb_user_out.value }}"

- name: Get mongodb user token
  k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ org_id }}-{{ env_id}}-mongodb-user-token"
  register: mongodb_user_token_out

- name: Set mongodb user name
  no_log: "{{hide_sensitive_logs}}"
  set_fact:
    mongodb_user: "{{mongodb_user_token_out.value }}"

- name: Set vault config from credential base64 encoded
  no_log: "{{hide_sensitive_logs}}"
  set_fact:
    vault_config: "{{ vault_config | b64decode | string }}"