---
- name: "Setup"
  include_tasks: setup.yml
  when: git_setup | default(true)

- name: "Pull"
  include_tasks: pull.yml
  when: git_pull | default(true)

- name: "Push"
  include_tasks: push.yml
  when: git_push | default(false)

- name: "Cleanup"
  include_tasks: cleanup.yml
  when: git_cleanup | default(false)
