---
- name: "Fail if main_domain does not exist"
  fail:
    msg: "'main_domain' not set"
  when: not main_domain

- name: "Set facts"
  include_tasks: set_facts.yml

- name: "Create hosted zone"
  include_tasks: create-zone.yml
  vars:
    subdomain: "{{resource_domain}}"
  loop:
    - "{{applications_domain}}"
    - "{{console_domain}}"
  loop_control:
    loop_var: resource_domain
