---
- name: Generate aws resource policy from template aws_resource_policy.json.j2
  template:
    src: templates/aws_resource_policy.json.j2
    dest: ./aws_resource_policy.json
    mode: 0755

- name: Create namespace
  k8s:
    state: present
    definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ mongodb.namespace }}"

- name: mongodb Helm chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
  tags:
    - mongodb
    - mongodb-helm-repo

- name: Install mongodb helm chart
  kubernetes.core.helm:
    chart_ref: bitnami/mongodb
    release_name: "{{ org_id }}"
    release_state: present
    release_namespace: "{{ mongodb.namespace }}"
    force: True
    wait: True
    wait_timeout: "300s"
    update_repo_cache: True
    disable_hook: True
    release_values:
      architecture: replicaset
      useStatefulSet: true
      auth:
        enabled: true
        rootPassword: "{{ mongodb_root_token }}"
        username: "{{ mongodb_user }}"
        password: "{{ mongodb_user_token }}"
        database: "{{ mongodb_database }}"
      persistence:
        enabled: true
        size: 20Gi
        mountPath: "/bitnami/mongodb"
        storageClass: "openidl-sc"
      serviceAccount:
        create: true
        name: "{{ org_id }}mongodbsvcuser"
      externalAccess:
        enabled: false
        service:
          type: ClusterIP
      replicaSetHostnames: true
      replicaCount: 3
      tls:
        enabled: false
      readinessProbe:
        enabled: false
      arbiter:
        livenessProbe:
          enabled: false
      global:
        namespaceOverride: "{{ mongodb.namespace }}"
  tags:
    - mongodb
    - mongodb-helm

- name: "Store access credentials "
  include_tasks: "store-access-{{ mongodb_access_store_type }}.yaml"