---
- name: "Import Export Organisation"
  hosts: all
  tasks:
    - include_role:
        name: git-config

    - name: "Blockchain collection"
      include_role:
        name: setup/blockchain-platform
      vars:
        blockchain_collection_install: true

    - name: "Import Export Organisation role"
      include_role:
        name: hlf/import-export-organisation
      vars:
        # common
        api_endpoint: "{{ console_api_endpoint }}"
        api_authtype: "{{ console_api_authtype }}"
        api_key: "{{ console_username }}"
        api_secret: "{{ console_password }}"
        organization_name: "{{ ord_organization_name }}"
