---
- name: "Create the channel"
  hosts: all
  tasks:
    - name: "Blockchain collection"
      include_role:
        name: setup/blockchain-platform
      vars:
        blockchain_collection_install: true

    - name: "Import vars from git"
      include_role:
        name: import-config-vars

    - name: "Create channel"
      include_role:
        name: hlf/create-channel
