---
- name: Join the channel
  hosts: all
  gather_facts: false
  tasks:
    - name: "Import vars from git"
      include_role:
        name: import-config-vars
    - name: "Blockchain collection"
      include_role:
        name: setup/blockchain-platform
      vars:
        blockchain_collection_install: false
    - include_role:
        name: hlf/peer-to-channel
