#
# SPDX-License-Identifier: Apache-2.0
#
# Usage:
# Create: ansible-playbook role_fabric_console.yml --extra-vars "state=present"
# Delete: ansible-playbook role_fabric_console.yml --extra-vars "state=absent"
---
- name: Deploy Fabric Operator
  hosts: ansible_provisioners
  collections:
    - kubernetes.core.k8s
    - kubernetes.core.k8s_info

  tasks:
    - include_role:
        name: "git-config"
    - set_fact:
        cluster: "d1-test-blk-cluster"
    - include_role:
        name: "setup/switch-cluster"
    - include_role:
        name: "include-config-vars"
    # - include_role:
    #     name: "fabric-operator"
    - include_role:
        name: "fabric-console"

