- hosts: ansible_provisioners
  gather_facts: no
  no_log: "{{ no_ansible_log | default(false) }}"
  collections:
    - kubernetes.core
    - ibm.blockchain_platform
  tasks:
    - include_role:
        name: "git-config"

    - name: "Include vars from git"
      include_vars:
        file: "./roles_configs/an1/config.yml"

    - include_role:
        name: "prerun-job"

    - include_role:
        name: "openidl-config"

    - include_role:
        name: "openidl-secrets"
