#
# SPDX-License-Identifier: Apache-2.0
#
# Usage:
# Create: ansible-playbook role_fabric_console.yml --extra-vars "state=present"
# Delete: ansible-playbook role_fabric_console.yml --extra-vars "state=absent"
---
- name: Setup environment
  import_playbook: environment-setup.yaml

- name: Deploy Fabric Operator
  hosts: localhost
  vars_files:
    - deploy-fabric-operator-vars.yml
  vars:
    state: present
    wait_timeout: 3600
    k8s:
      cluster_name: d1-test-blk-cluster
    aws:
      access_id: {{aws_access_key}}
      access_key: {{aws_secret_key}}
      region: us-east-2
      external_id: {{aws_external_id}}
      assume_role_arn: {{aws_assume_role_arn}}

  roles:
    - fabric-operator
    - fabric-console
    - flux2
    - kubectl-config
