- hosts: ansible_provisioners
  gather_facts: false
  no_log: "{{ no_ansible_log | default(false) }}"
  tasks:
    - name: Checkout configuration

    - include_role:
        name: "import-config-vars"

    - include_role:
        name: "openidl-identities-deploy"
