---
- name: Manage local FluxCD
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
  vars:
    do: create
    wait_timeout: 3600
  roles:
      - role: flux

# ansible-playbook -i inventory  role_flux.yml -e do=create
# ansible-playbook -i inventory  role_flux.yml -e do=delete