---
- name: Create Kubernetes namespace
  k8s:
    name: "{{ application_namespace }}"
    kind: Namespace
    state: present
    wait: true
    wait_sleep: 2
    wait_timeout: 60

- name: Deploy openIDL app on Analytics node using helm
  shell: |
    helm upgrade --recreate-pods --install {{ env_id }}-{{ org_name }} {{app_chart_dest_folder}}/openidl-k8s \
    -f {{git_config_path}}/apps/app-global-values.yml -n {{ application_namespace }} \
    --set global.datacallapp.ingressenabled=true \
    --set global.utilities.ingressenabled=true \
    --set global.ui.ingressenabled=true \
    --set global.transactionaldataeventlistener.ingressenabled=true \
    --set global.insurancedatamanager.ingressenabled=true \
    --set global.secrets.install=false
  when: application_node_type == "analytics"

- name: Deploy openIDL app on Carrier node using helm
  shell: |
    helm upgrade --recreate-pods --install {{ env_id }}-{{ org_name }} {{app_chart_dest_folder}}/openidl-k8s \
    -f {{git_config_path}}/apps/app-global-values.yml -n {{ application_namespace }} \
    --set global.datacallapp.ingressenabled=true \
    --set global.utilities.ingressenabled=true \
    --set global.carrierui.ingressenabled=true \
    --set global.insurancedatamanager.ingressenabled=true \
    --set global.secrets.install=false
  when: application_node_type == "carrier"

- name: Annotate ingress
  shell: |
    kubectl -n {{ application_namespace }} annotate ingress kubernetes.io/ingress.class={{nginx_controller_name}} --all
  ignore_errors: yes 
