default_aws_profile: "cicd-role"
console_api_authtype: "basic"
cert_auth: "{{msp_id}}"
aws_region: "{{region}}"
s3_icon_bucket_url: "{{ org_id }}-{{ env_id }}-openidl-publicicons.s3.{{ region }}.amazonaws.com"
app_data_call_address: "data-call-app-service.{{ env_id }}.{{ domain }}"

network:
  org_name: "{{org_id}}"
  msp_id: "{{msp_id}}"
  channels: "{{fabric_channels}}"