---
- name: Update kubeconfig and set context to openidl {{ app_cluster_name }}
  shell: |
    export AWS_PROFILE=cicd-role; aws eks update-kubeconfig --region {{ aws_region }} --name {{ app_cluster_name }}

- name: Delete folder for HELM chart
  file:
   path: /tmp/openidl-code/helm
   state: absent

- name: Download HELM chart
  no_log: false
  shell: |
    git clone https://{{ gitrepo_name }} -b {{ gitrepo_branch }} /tmp/openidl-code/helm

- name: Deploy secrets
  shell: |
    helm upgrade --install \
              {{ env }}-{{ org_name }}-secrets /tmp/openidl-code/helm/openidl-k8s \
              -f /tmp/openidl-code/helm/openidl-k8s/global-values-secrets.yaml -n openidl \
            --set global.configpath=/tmp/openidl-code/{{ org_name }}-{{ env }}-config
  register: deploy_secrets

#- name: Dispose of temporary git repository content
#  file:
#   path: /tmp/openidl-code/
#   state: absent
