---
tmp_directory: "{{ lookup('env', 'TMPDIR') | default('/tmp',true) }}"

default:
  version: "1.25.6"
  os: "linux"    # use "darwin" for MacOS X, "windows" for Windows
  arch: "amd64"  # other possible values: "386","arm64","arm","ppc64le","s390x"
  bin_directory: "~/bin"  
  checksum: "sha256:ba876aef0e9d7e2e8fedac036ec194de5ec9b6d2953e30ff82a2758c6ba32174"
