---





- name: Discover endorsers for chaincode {{discovery_cc_id}} on channel {{ discovery_channel.channel }} with MSP {{discovery_msp}} and peer {{discovery_peer.host}}
  shell: >
    discover --peerTLSCA {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/tls/ca.crt --userKey {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/msp/keystore/key.key --userCert {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/msp/signcerts/cert.pem --MSP {{discovery_msp}} --tlsCert {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/tls/cert.crt --tlsKey {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/tls/key.key endorsers --channel {{ discovery_channel.channel }}  --server {{discovery_peer.host}}:{{discovery_peer.port}} --chaincode {{discovery_cc_id}}
  register: endorsersOutput
  environment:
    PATH: "{{ fab_home_folder }}/current/bin"
  when: discovery_cc_id is defined

- set_fact:
    discovery_endorsers: "{{endorsersOutput.stdout | from_json}}"
  when: discovery_cc_id is defined


- name: Discover endorsers for chaincode {{discovery_cc_id}} on channel {{ discovery_channel.channel }} with MSP {{discovery_msp}} and peer {{discovery_peer.host}}
  shell: >
    discover --peerTLSCA {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/tls/ca.crt --userKey {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/msp/keystore/key.key --userCert {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/msp/signcerts/cert.pem --MSP {{discovery_msp}} --tlsCert {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/tls/cert.crt --tlsKey {{ local_pki_folder }}/{{ discovery_msp_domain }}/users/peerAdmin/tls/key.key peers --channel {{ discovery_channel.channel }}  --server {{discovery_peer.host}}:{{discovery_peer.port}}
  register: endorsersOutput
  environment:
    PATH: "{{ fab_home_folder }}/current/bin"
  when: discovery_discover_peers is defined

- set_fact:
    discovery_peers: "{{endorsersOutput.stdout | from_json}}"
  when: discovery_discover_peers is defined
