- name: "Get the organization"
  ibm.blockchain_platform.organization_info:
    api_endpoint: "{{ api_endpoint }}"
    api_authtype: "{{ api_authtype }}"
    api_key: "{{ api_key }}"
    api_secret: "{{ api_secret | default(omit) }}"
    api_token_endpoint: "{{ api_token_endpoint | default(omit) }}"
    name: "{{ msp_peer.MSPID }}"
  register: result


- name: "Fail if organization not found {{msp_peer.MSPID}}"
  fail:
    msg: "Organization {{ msp_peer.MSPID }} not found in console"
  when: not result

# Store the MSP CA TLS certs in a file
- copy:
    content: "{{ result.tls_root_certs | b64decode }}"
    dest: "{{config_folder}}/{{msp_id}}/{{msp_peer.MSPID}}_tls_ca_root.pem"

 